#Hypothesis: Higher elevation is positively correlated with lower overall weight of Acanthis flammea bird species. 
#The average elevation in which Acanthis flammea have been sighted have decreased from 1992-2007, 
#thus decreasing their average weight from 1992-2007. 
#Null Hypothesis: There is no correlation between weight and elevation, and elevation has not decreased overtime.

getwd()
data<-read.csv("~/Desktop/Evolution/Tasks/NP/Data/BirdData2.csv")
plot(data$elev, data$weight, xlim=c(15, 950), xlab="Elevation", ylab="Weight in grams")

data1992<-read.csv("~/Desktop/Evolution/Tasks/NP/Data/1992BirdData.csv")
data1993<-read.csv("~/Desktop/Evolution/Tasks/NP/Data/1993BirdData.csv")
data1994<-read.csv("~/Desktop/Evolution/Tasks/NP/Data/1994BirdData.csv")
data1995<-read.csv("~/Desktop/Evolution/Tasks/NP/Data/1995BirdData.csv")
data1996<-read.csv("~/Desktop/Evolution/Tasks/NP/Data/1996BirdData.csv")
data1997<-read.csv("~/Desktop/Evolution/Tasks/NP/Data/1997BirdData.csv")
data1998<-read.csv("~/Desktop/Evolution/Tasks/NP/Data/1998BirdData.csv")
data1999<-read.csv("~/Desktop/Evolution/Tasks/NP/Data/1999BirdData.csv")
data2000<-read.csv("~/Desktop/Evolution/Tasks/NP/Data/2000BirdData.csv")
data2001<-read.csv("~/Desktop/Evolution/Tasks/NP/Data/2001BirdData.csv")
data2002<-read.csv("~/Desktop/Evolution/Tasks/NP/Data/2002BirdData.csv")
data2006<-read.csv("~/Desktop/Evolution/Tasks/NP/Data/2006BirdData.csv")
data2007<-read.csv("~/Desktop/Evolution/Tasks/NP/Data/2007BirdData.csv")
pdf("1992 Elevation vs Weight.pdf")
plot(data1992$elev, data1992$weight, xlab="Elevation", ylab="Weight in grams")
title('1992 Elevation vs. Weight')
dev.off()
pdf("1993 Elevation vs Weight.pdf")
plot(data1993$elev, data1993$weight, xlab="Elevation", ylab="Weight in grams")
title('1993 Elevation vs. Weight')
dev.off()
pdf("1994 Elevation vs Weight.pdf")
plot(data1994$elev, data1994$weight, xlab="Elevation", ylab="Weight in grams")
title('1994 Elevation vs. Weight')
dev.off()
plot(data1995$elev, data1995$weight, xlab="Elevation", ylab="Weight in grams")
title('1995 Elevation vs. Weight')
plot(data1996$elev, data1996$weight, xlab="Elevation", ylab="Weight in grams")
title('1996 Elevation vs. Weight')
plot(data1997$elev, data1997$weight, xlab="Elevation", ylab="Weight in grams")
title('1997 Elevation vs. Weight')
plot(data1998$elev, data1998$weight, xlab="Elevation", ylab="Weight in grams")
title('1998 Elevation vs. Weight')
plot(data1999$elev, data1999$weight, xlab="Elevation", ylab="Weight in grams")
title('1999 Elevation vs. Weight')
plot(data2000$elev, data2000$weight, xlab="Elevation", ylab="Weight in grams")
title('2000 Elevation vs. Weight')
plot(data2001$elev, data2001$weight, xlab="Elevation", ylab="Weight in grams")
title('2001 Elevation vs. Weight')
plot(data2002$elev, data2002$weight, xlab="Elevation", ylab="Weight in grams")
title('2002 Elevation vs. Weight')
plot(data2006$elev, data2006$weight, xlab="Elevation", ylab="Weight in grams")
title('2006 Elevation vs. Weight')
plot(data2007$elev, data2007$weight, xlab="Elevation", ylab="Weight in grams")
title('2007 Elevation vs. Weight')
plot(data$year, data$elev, xlab="Year",ylab="Elevation")
title('Changes in Elevation from 1992-2007')
plot(data$year, data$weight, xlab="Year", ylab="Weight")
title('Changes in Weight from 1992-2007')
cor.test(data$elev, data$weight, method=c("pearson", "kendall", "spearman"))
cor.test(data$year, data$elev, method=c("pearson", "kendall", "spearman"))
cor.test(data$year, data$weight, method=c("pearson", "kendall", "spearman"))
